shell /usr/bin/fish

# FONT
font_family FiraCode-Retina

# Background
background_image ~/Pictures/Backgrounds/background6_blurred.jpg
background_image_layout scaled
#background_opacity 0.9
#dynamic_background_opacity yes
#background_blur 1
#background_tint 0.9

# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME
