require("config.settings")
require("config.lazy")
require("config.keymaps")
require("config.lsp")
require("config.diagnostic")
require("config.cmp")
require("config.formatter")
require("config.commands")
